stages:
  download_onet_data:
    cmd: wget https://www.onetcenter.org/dl_files/database/db_20_1_text/Sample%20of%20Reported%20Titles.txt
      -O data/onet_data.txt
    outs:
    - data/onet_data.txt
  download_onet_job_titles:
    cmd: wget https://www.onetcenter.org/dl_files/database/db_25_0_text/Occupation%20Data.txt
      -O data/onet_job_titles.txt
    outs:
    - data/onet_job_titles.txt
  modify_data:
    cmd: python src/modify_data.py
    deps:
    - data/onet_data.txt
    - data/onet_job_titles.txt
    - src/modify_data.py
    outs:
    - data/modified_data.csv
  classify_and_pickle:
    cmd: python src/classify_and_pickle.py
    deps:
    - data/modified_data.csv
    - src/classify_and_pickle.py
    - src/soc_classifier.py
    outs:
    - models/soc_code_model.pickle
    - models/soc_high_level_model.pickle
    - models/soc_major_model.pickle
